#!/bin/bash
# List chezmoi managed configuration files
set -Eeuo pipefail

(
    cd "$(chezmoi source-path)" && \
        find -type f -not -path "*/tpm/*" -not -path "*/.git/*" | \
        grep -Ev '\./(\.|Makefile|README|run_)' | \
        sed -E '/symlink/d; s!^\.!~!; s!dot_!.!g; s!([a-z]+_)!!g'
)
