#!/bin/bash
# Refresh a command on a regular basis without flickering
set -Eeuo pipefail

#########
# USAGE #
#########

usage() {
    echo "Usage: $(basename "${0}") [OPTIONS] COMMAND [ARGS...]

Refresh a command on a regular basis without flickering.

OPTIONS:
    -r SECONDS  Refresh rate in seconds
    -h          Display this message"
}

###################
# OPTIONS PARSING #
###################

RATE=0.5

while getopts 'r:h' opts ; do
    case "${opts}" in
        r)
            RATE="${OPTARG}"
            ;;
        h)
            usage
            exit 1
            ;;
        ?)
            usage
            exit 1
            ;;
    esac
done
shift "$((OPTIND - 1))"

########
# TRAP #
########

# Unhide cursor on exit
unhide_cursor() {
    printf '\e[?25h'
}
trap unhide_cursor EXIT

###########
# ACTIONS #
###########

# Clear the screen initially
clear

# Hide the cursor
printf '\e[?25l'

# Display loop
while true ; do
    # Move cursor to the top of the screen without clearing
    printf '\033[;H'
    # Run command
    "${@}" || true
    # Wait
    sleep "${RATE}"
done
