#!/bin/bash
# Refresh a command on a regular basis without flickering
set -Eeuo pipefail

###############
# DEFINITIONS #
###############

RATE=0.5
CLEAR_ITER=60

#########
# USAGE #
#########

usage() {
    echo "Usage: $(basename "${0}") [OPTIONS] COMMAND [ARGS...]

Refresh a command on a regular basis without flickering.

OPTIONS:
    -r SECONDS  Refresh rate in seconds (default is ${RATE})
    -c NUMBER   Fully clear every N iteration (default is ${CLEAR_ITER})
    -h          Display this message"
}

###################
# OPTIONS PARSING #
###################

while getopts 'r:c:h' opts ; do
    case "${opts}" in
        r)
            RATE="${OPTARG}"
            ;;
        c)
            CLEAR_ITER="${OPTARG}"
            ;;
        h)
            usage
            exit 1
            ;;
        ?)
            usage
            exit 1
            ;;
    esac
done
shift "$((OPTIND - 1))"

########
# TRAP #
########

# Unhide cursor on exit
unhide_cursor() {
    printf '\e[?25h'
}
trap unhide_cursor EXIT

###########
# ACTIONS #
###########

# Clear the screen initially
clear

# Hide the cursor
printf '\e[?25l'

# Display loop
n=1
while true ; do
    # Move cursor to the top of the screen without clearing
    printf '\033[;H'
    # Run command
    "${@}" || true
    # Clear every N iterations
    if [[ "${n}" -eq "${CLEAR_ITER}" ]] ; then
        clear
        n=0
    else
        n=$((n+1))
    fi
    # Wait
    sleep "${RATE}"
done
