#!/usr/bin/env bash

SCRIPT_DIR="$( dirname "${BASH_SOURCE[0]}" )"
CONFIG_FILE="${SCRIPT_DIR}/tools.source"

source "${CONFIG_FILE}"

TOOL="${1:-}"

if [[ -n "${TOOL}" ]] ; then
    # Run tool
    "${TOOLS["${TOOL}"]}" "${@:2}"
else
    # List tools
    echo "${!TOOLS[@]}" | tr " " $"\n" | sort
fi
