#!/bin/bash
# Setup monitors with wlr-randr
set -Eeuo pipefail

MONITORS="$(wlr-randr | grep -o '^[^ ]*')"

# Set monitors
if grep -q '^DP-4$' <<< "${MONITORS}" && grep -q '^DP-5$' <<< "${MONITORS}" ; then
    echo "Setting monitors in office configuration (docked)"
    wlr-randr \
        --output eDP-1 --on --mode 3456x2160@60.000999Hz --pos 1600,1440 --scale 2 \
        --output DP-4 --on --mode 2560x1440@59.951000Hz --pos 0,0 --scale 1 \
        --output DP-5 --on --mode 2560x1440@59.951000Hz --pos 2560,0 --scale 1
elif grep -q '^DP-2$' <<< "${MONITORS}" && grep -q '^DP-3$' <<< "${MONITORS}" ; then
    echo "Setting monitors in home configuration for work laptop (docked)"
    wlr-randr \
        --output eDP-1 --off \
        --output DP-2 --on --mode 3840x1600@60.000999Hz --pos 1080,0 --transform normal --scale 1 \
        --output DP-3 --on --mode 1920x1080@60.000000Hz --pos 0,0 --transform 270 --scale 1
elif grep -q '^DP-1$' <<< "${MONITORS}" && [[ "${HOSTNAME}" = "laptop-home" ]] ; then
    echo "Setting monitors in home configuration for home laptop (docked)"
    # xrandr \
    #     --output eDP-1 --off \
    #     --output HDMI-1 --off \
    #     --output HDMI-2 --off \
    #     --output DP-1 --mode 3840x1600 --pos 0x0 --rotate normal \
    #     --output DP-2 --off \
    #     --output DP-1-1 --off \
    #     --output DP-1-2 --off \
    #     --output DP-1-3 --off
else
    echo "Setting monitors in default configuration (undocked)"
    wlr-randr \
        --output eDP-1 --on --mode 3456x2160@60.000999Hz --pos 0,0 --scale 2
fi
