#!/bin/bash
# Setup monitors with xrandr
set -Eeuo pipefail

MONITORS="$(xrandr --query | grep -o '^[^ ]* connected' | cut -d' ' -f1)"

# Set monitors
if [[ "${MONITORS}" == *"DP-1-1"* && "${MONITORS}" == *"DP-1-2"* ]]; then
    # Docked
    xrandr --output eDP-1 --off
    xrandr --output HDMI-1 --off
    xrandr --output HDMI-2 --off
    xrandr --output DP-1 --off
    xrandr --output DP-1-1 --mode 1920x1080 --pos 0x0 --rotate right
    xrandr --output DP-1-2 --primary --mode 3840x1600 --pos 1080x0 --rotate normal
    xrandr --output DP-1-3 --off
else
    # Undocked
    xrandr --output eDP-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal
    xrandr --output DP-1-1 --off
    xrandr --output DP-1-2 --off
fi

# Start polybar
~/.config/polybar/launch.sh

# Reload wallapper
,wallpaper-set -r
