#!/bin/bash
# Setup monitors with xrandr
set -Eeuo pipefail

MONITORS="$(xrandr --query | grep -o '^[^ ]* connected' | cut -d' ' -f1)"

# Set monitors
if [[ "${MONITORS}" == *"DP-1-1"* && "${MONITORS}" == *"DP-1-2"* ]]; then
    # Docked at the office
    xrandr \
        --output eDP-1 --primary --mode 1920x1080 --pos 1600x1440 --rotate normal \
        --output HDMI-1 --off \
        --output HDMI-2 --off \
        --output DP-1 --off \
        --output DP-2 --off \
        --output DP-1-1 --mode 2560x1440 --pos 0x0 --rotate normal \
        --output DP-1-2 --mode 2560x1440 --pos 2560x0 --rotate normal \
        --output DP-1-3 --off
else
    # Undocked
    xrandr \
        --output eDP-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal \
        --output HDMI-1 --off \
        --output HDMI-2 --off \
        --output DP-1 --off \
        --output DP-2 --off \
        --output DP-1-1 --off \
        --output DP-1-2 --off \
        --output DP-1-3 --off
fi

# Start polybar
~/.config/polybar/launch.sh

# Reload wallapper
# ,wallpaper-set -r
