#!/bin/bash
# Setup monitors with xrandr
set -Eeuo pipefail

MONITORS="$(xrandr --query | grep -o '^[^ ]* connected' | cut -d' ' -f1)"

# Set monitors
if grep -q '^DP-1-1$' <<< "${MONITORS}" && grep -q '^DP-1-2$' <<< "${MONITORS}" ; then
    echo "Setting monitors in office configuration (docked)"
    xrandr \
        --output eDP-1 --primary --mode 1920x1080 --pos 1600x1440 --rotate normal \
        --output HDMI-1 --off \
        --output HDMI-2 --off \
        --output DP-1 --off \
        --output DP-2 --off \
        --output DP-1-1 --mode 2560x1440 --pos 0x0 --rotate normal \
        --output DP-1-2 --mode 2560x1440 --pos 2560x0 --rotate normal \
        --output DP-1-3 --off
elif grep -q '^DP-1$' <<< "${MONITORS}" && grep -q '^DP-2$' <<< "${MONITORS}" ; then
    echo "Setting monitors in home configuration (docked)"
    xrandr \
        --output eDP-1 --off \
        --output HDMI-1 --off \
        --output HDMI-2 --off \
        --output DP-1 --mode 1920x1080 --pos 0x0 --rotate right \
        --output DP-2 --mode 3840x1600 --pos 1080x0 --rotate normal \
        --output DP-1-1 --off \
        --output DP-1-2 --off \
        --output DP-1-3 --off
else
    echo "Setting monitors in default configuration (undocked)"
    xrandr \
        --output eDP-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal \
        --output HDMI-1 --off \
        --output HDMI-2 --off \
        --output DP-1 --off \
        --output DP-2 --off \
        --output DP-1-1 --off \
        --output DP-1-2 --off \
        --output DP-1-3 --off
fi

# Start polybar
~/.config/polybar/launch.sh

# Reload wallapper
# ,wallpaper-set -r
