#!/bin/bash
# Launch applications from .desktop files
# Uses freedesktop2launcher binary to find and parse desktop files

FZF_CMD=("fzf" "--info" "hidden" "--reverse" "--delimiter" "\t" "--with-nth" "2" "--preview-window" "up,1" "--preview" "echo {3}")
TERMINAL_CMD="${TERMINAL} -e"

removeFieldCodes() {
    sed 's/%[[:alpha:]]//g'
}

SELECTED="$(freedesktop2launcher | "${FZF_CMD[@]}")"
EXECUTABLE="$(cut -d $'\t' -f 4 <<< "${SELECTED}" | removeFieldCodes)"

# Check if it needs to be run in a terminal
[ "$(cut -d $'\t' -f 5 <<< "${SELECTED}")" = true ] && EXECUTABLE="${TERMINAL_CMD} ${EXECUTABLE}"

# Start application and detach
setsid /bin/sh -c "${EXECUTABLE}" >&/dev/null </dev/null &
sleep 0.01
