#!/bin/bash
# Launch applications from .desktop files

FZF_CMD=("fzf" "--delimiter" "\t" "--with-nth" "3" "--preview" "bat {1}")
TERMINAL_CMD="${TERMINAL} -e"

findDesktopFiles() {
    local application_dirs=()
    readarray -d ':' -t share_dirs <<< "${XDG_DATA_HOME-${HOME}/.local/share}:${XDG_DATA_DIRS-/usr/local/share:/usr/share}"
    for share_dir in "${share_dirs[@]}" ; do
        # Append to existing array with -O option (start index)
        readarray -t -O "${#application_dirs[@]}" application_dirs < <(find "${share_dir%/}/applications" -type d 2>/dev/null)
    done
    find "${application_dirs[@]}" -type f -name '*.desktop'
}

parseDesktopFiles() {
    while read -r file ; do
        name="$(sed -En 's!^Name[[:space:]]*=[[:space:]]*(.+)!\1!p' "${file}")"
        executable="$(sed -En 's!^Exec[[:space:]]*=[[:space:]]*(.+)!\1!p' "${file}")"
        terminal="$(sed -En 's!^Terminal[[:space:]]*=[[:space:]]*(.+)!\1!p' "${file}")"
        [[ "${terminal}" = true ]] && executable="${TERMINAL_CMD} ${executable}"
        echo -e "${file}\t${executable}\t${name}"
    done
}

SELECTED=$(findDesktopFiles | parseDesktopFiles | "${FZF_CMD[@]}" | cut -d $'\t' -f2)

# Start application and detach
setsid /bin/sh -c "${SELECTED}" >&/dev/null </dev/null &
sleep 0.01
