#!/bin/bash
# Copy from clipboard history

CLIPBOARD_HISTORY_CMD=("cliphist" "list")
CLIPBOARD_COPY_CMD=("wl-copy" "--foreground")

# Select a specific cheatsheet item and copy it
FZF_CMD=("fzf" "--info" "inline" "--reverse")
SELECTED="$("${CLIPBOARD_HISTORY_CMD[@]}" | sed -E 's/[0-9]+\. //' | "${FZF_CMD[@]}")"

[ -z "${SELECTED}" ] && exit 2

setsid "${CLIPBOARD_COPY_CMD[@]}" "${SELECTED}" >&/dev/null </dev/null &
sleep 0.01
