#!/bin/bash
# Open GitLab MR to be reviewed in browser

SCRIPT_DIR="$( dirname "${BASH_SOURCE[0]}" )"

PREVIEW_CMD="echo -e 'Project:\t{1}\nCreated:\t{7}\nUpdated:\t{8}\nState:\t\t{5}\nAssignees:\t{3}\nReviewers:\t{4}'"
FZF_CMD=("fzf" "--bind" "ctrl-w:reload(source ${HOME}/.asdf/asdf.sh && ${SCRIPT_DIR}/_gitlab --withDrafts)" "--read0" "--info" "hidden" "--reverse" "--delimiter" "\t" "--with-nth" "2" "--preview-window" "up,6" "--preview" "${PREVIEW_CMD}")

SELECTED_URL="$("${SCRIPT_DIR}/_gitlab" | "${FZF_CMD[@]}" | cut -d $'\t' -f 6)"

[[ -z "${SELECTED_URL}" ]] && exit 0

# Open MR URL in browser
"${BROWSER}" "${SELECTED_URL}"
