#!/bin/bash
# Open PDF file(s) in PDF viewer

FZF_CMD=("fzf" "--multi" "--info" "inline" "--reverse" "--delimiter" "/" "--with-nth" "-1")

readarray -t SELECTED < <(fd --no-ignore --extension pdf . ~ | "${FZF_CMD[@]}")

# Start application and detach
[ "${#SELECTED[@]}" -ne 0 ] && setsid "${READER}" "${SELECTED[@]}" >&/dev/null </dev/null &
sleep 0.01
