#!/bin/bash
# Perform power-related actions

FZF_CMD=("fzf" "--info" "hidden" "--reverse" "--delimiter" "\t" "--with-nth" "1")

read -r -d '' LIST <<'EOF'
Lock\tswaylock --daemonize --color 000000
Suspend\tsystemctl suspend
Reboot\tsystemctl reboot
Power-off\tsystemctl poweroff
Log out\tswaymsg exit
EOF

SELECTED="$(echo -e "${LIST}" | "${FZF_CMD[@]}" | cut -d $'\t' -f2)"

# Run command and detach
setsid /bin/sh -c "${SELECTED}" >&/dev/null </dev/null &
sleep 0.01
