#!/bin/bash
# Open project(s) in VSCode

GIT_LOG_CMD="test -d {} && git -C {} log --all --decorate --oneline --color=always -- | head -n3"
FZF_CMD=("fzf" "--multi" "--info" "inline" "--reverse" "--delimiter" "/" "--with-nth" "-1" "--preview-window" "up,4" "--bind" "ctrl-w:reload(fd --no-ignore --hidden '.code-workspace$' ~/Projects/ ~/Sources/)" "--preview" "echo -e '\033[0;36m{}\033[0m'; ${GIT_LOG_CMD}")
VSCODE_CMD=("code" "--new-window")

readarray -t SELECTED < <(fd --no-ignore --hidden '(.git|.code-workspace)$' ~/Projects/ ~/Sources/ | sed 's!/.git$!!' | "${FZF_CMD[@]}")

# Start application and detach
[ "${#SELECTED[@]}" -ne 0 ] && setsid "${VSCODE_CMD[@]}" "${SELECTED[@]}" >&/dev/null </dev/null &
sleep 0.01
